# Generated by Django 3.2.15 on 2022-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_cafepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='tpic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='travelpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='tpostpic')),
                ('desc1', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='cafemodel',
        ),
        migrations.DeleteModel(
            name='cafepost',
        ),
    ]
